function [hEdit1,hEdit2,hButtonGo,hButtonClf,activeSubplot]=disp_ui(hFig)

uicontrol(hFig,'style','text','position',[20,160,40,20],'string','S')
uicontrol(hFig,'style','text','position',[20,120,40,20],'string','T')


hEdit1 = uicontrol(hFig,'style','edit','position',[70,160,120,20],...
    'string','0.005','BackgroundColor','w');
hEdit2 = uicontrol(hFig,'style','edit','position',[70,120,120,20],...
    'string','0.4','BackgroundColor','w');

hButtonGo = uicontrol(hFig,'style','pushbutton','position',[70,80,40,20],...
                     'string','Go',...
                     'Callback','activeSubplot=plot_mancal_callback(hEdit1, hEdit2,activeSubplot,TS,TM,H);');
hButtonClf = uicontrol(hFig,'style','pushbutton','position',[20,80,40,20],...
                     'string','Reset',...
                     'Callback', ['figure(hFig),clf,[hEdit1,hEdit2,hB',...
                     'uttonGo,hButtonClf,activeSubplot]=disp_ui(hFig);']);
                 

activeSubplot = 1;